#!/usr/bin/env python3
"""Generate rdfs:domain triples for IATA-1R-DM-Ontology.ttl (gh#93).

The vendored IATA ONE Record mirror encodes property domains as a
non-standard ``owl:comment "Domain :ClassName"@en`` annotation instead of
``rdfs:domain``, so every rdfs:domain-based consumer (including the
toolkit) sees zero properties on every ONE Record class. The mirror is
never hand-edited (see authoritative-ontologies/IATA/README.md); this
script derives the missing rdfs:domain triples into a separate,
regenerated sidecar file instead.

Regenerate after every IATA vendor refresh:
    python scripts/generate_iata_domain_patch.py
"""
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
IATA_DIR = (
    REPO_ROOT
    / "kairos_ontology_referencemodels"
    / "ontology-reference-models"
    / "authoritative-ontologies"
    / "IATA"
    / "current"
)
SOURCE_TTL = IATA_DIR / "IATA-1R-DM-Ontology.ttl"
OUTPUT_TTL = IATA_DIR / "IATA-1R-DM-Ontology.domains-patch.ttl"

CARGO_ONTOLOGY_IRI = "https://onerecord.iata.org/ns/cargo"
VENDOR_MIRROR_ONTOLOGY_IRI = "https://onerecord.iata.org/ns/cargo-vendor-mirror"

PROPERTY_START_RE = re.compile(
    r'^(?P<prop>:[A-Za-z][\w-]*)\s+rdf:type\s+owl:(?:ObjectProperty|DatatypeProperty)\s*;\s*$'
)
BLOCK_END_RE = re.compile(r'\s\.\s*$')

# One or more comma-separated string literals following the owl:comment predicate.
OWL_COMMENT_RE = re.compile(
    r'owl:comment\s+(?P<lits>"(?:[^"\\]|\\.)*"(?:@[A-Za-z-]+)?'
    r'(?:\s*,\s*"(?:[^"\\]|\\.)*"(?:@[A-Za-z-]+)?)*)\s*[;.]'
)
LITERAL_RE = re.compile(r'"(?P<text>(?:[^"\\]|\\.)*)"')
# Tolerates the missing-colon-before-class typo ("Domain: X") seen once in the
# vendor file, and the bare owl:Thing universal-domain token used ~20 times.
DOMAIN_TEXT_RE = re.compile(
    r'^\s*Domain\s*:?\s*(?P<cls>owl:Thing|[A-Za-z][\w-]*)\s*$', re.IGNORECASE
)


def extract_property_blocks(text: str):
    """Yield (property_name, block_text) for each owl:ObjectProperty/DatatypeProperty block."""
    lines = text.splitlines()
    index = 0
    while index < len(lines):
        match = PROPERTY_START_RE.match(lines[index])
        if not match:
            index += 1
            continue
        prop = match.group("prop")
        block_lines = [lines[index]]
        index += 1
        while index < len(lines) and not BLOCK_END_RE.search(block_lines[-1]):
            block_lines.append(lines[index])
            index += 1
        yield prop, "\n".join(block_lines)


def domains_for_block(block_text: str):
    """Return the list of domain class tokens (e.g. ':Waybill', 'owl:Thing') found in a block."""
    comment_match = OWL_COMMENT_RE.search(block_text)
    if not comment_match:
        return []
    domains = []
    for literal_match in LITERAL_RE.finditer(comment_match.group("lits")):
        domain_match = DOMAIN_TEXT_RE.match(literal_match.group("text"))
        if domain_match:
            cls = domain_match.group("cls")
            domains.append(cls if cls.startswith("owl:") else f":{cls.lstrip(':')}")
    return domains


def main():
    text = SOURCE_TTL.read_text(encoding="utf-8")

    total = 0
    unmatched = []
    multi_domain = []
    thing_domain = []
    triples = []

    for prop, block in extract_property_blocks(text):
        total += 1
        domains = domains_for_block(block)
        if not domains:
            unmatched.append(prop)
            continue
        if len(domains) > 1:
            multi_domain.append(prop)
        for cls in domains:
            if cls == "owl:Thing":
                thing_domain.append(prop)
            triples.append((prop, cls))

    matched = total - len(unmatched)
    print(f"properties total:        {total}")
    print(f"properties matched:      {matched}")
    print(f"multi-domain properties: {len(multi_domain)} {multi_domain}")
    print(f"owl:Thing-domain uses:   {len(thing_domain)}")
    print(f"unmatched properties:    {len(unmatched)} {unmatched}")

    lines = [
        "# GENERATED by scripts/generate_iata_domain_patch.py -- do not hand-edit.",
        "# Regenerate on every IATA vendor refresh (see METADATA.txt \"deviations\").",
        "#",
        "# Derives rdfs:domain triples for https://onerecord.iata.org/ns/cargo#",
        "# properties from the vendor mirror's non-standard",
        "# `owl:comment \"Domain :ClassName\"@en` annotations (gh#93). The upstream",
        "# IATA-1R-DM-Ontology.ttl mirror is never hand-edited; this file supplies",
        "# what rdfs:domain-based consumers (including the toolkit) need, and is",
        "# wired in via a catalog-v001.xml redirection so no data-domains.yaml",
        "# import needs to change.",
        "#",
        f"# {total} properties in the vendor mirror; {matched} matched a domain",
        f"# ({len(multi_domain)} multi-domain, {len(thing_domain)} owl:Thing);",
        f"# {len(unmatched)} left without a resolvable domain (left as-is, not guessed):",
    ]
    for prop in unmatched:
        lines.append(f"#   {prop}")
    lines += [
        "",
        "@prefix : <https://onerecord.iata.org/ns/cargo#> .",
        "@prefix owl: <http://www.w3.org/2002/07/owl#> .",
        "@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .",
        "",
        f"<{CARGO_ONTOLOGY_IRI}> a owl:Ontology ;",
        f"    owl:imports <{VENDOR_MIRROR_ONTOLOGY_IRI}#> .",
        "",
    ]
    for prop, cls in triples:
        lines.append(f"{prop} rdfs:domain {cls} .")
    lines.append("")

    OUTPUT_TTL.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {len(triples)} rdfs:domain triples to {OUTPUT_TTL}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
