# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 Cnext.eu
#!/usr/bin/env python3
"""Generate Mermaid class diagrams for each derived ontology suite.

Why this exists
---------------
The repository ships nine derived ontology suites, but nothing showed *at a glance* what
classes a suite contains or how they relate. Business and onboarding conversations were
reconstructing that picture by reading Turtle by hand. A hand-drawn diagram would rot the
moment a class was added — the exact failure mode ``CONTRACT.md`` warns about ("derived facts
are generated or tested, never hand-maintained").

So the per-suite class diagrams are **generated from the Turtle**, never hand-edited. This
script parses every ``current/**/*.ttl`` in a suite with ``rdflib`` and renders a Mermaid
``classDiagram`` capturing:

  * every ``owl:Class`` as a node (with a compact datatype-attribute count),
  * ``rdfs:subClassOf`` between named classes as inheritance edges,
  * ``owl:ObjectProperty`` ``rdfs:domain -> rdfs:range`` as labelled associations,
  * classes owned by *other* suites (reached across a suite boundary) as external stubs.

Output lands under ``ontology-reference-models/diagrams/generated/`` behind a GENERATED
banner. A full run also writes a raw ``.mmd`` sibling next to every diagram ``.md`` (generated
and hand-authored conceptual alike) — plain Mermaid with no markdown fence, extracted from the
committed ``.md`` so it can be loaded straight into mermaid.live or ``mmdc``. ``--check``
re-renders in memory and diffs against disk without writing — the same contract as
``generate_pack_docs.py --check`` — so CI fails when a suite changes and its diagram (or its
``.mmd`` export) was not regenerated.

The hand-authored *conceptual* diagrams live next door in ``diagrams/conceptual/`` and are
never touched by this script.

Usage:
    python scripts/generate_ontology_diagrams.py                 # rewrite all suites in place
    python scripts/generate_ontology_diagrams.py --check         # fail if anything is stale
    python scripts/generate_ontology_diagrams.py --suite DCSA    # one suite only
    python scripts/generate_ontology_diagrams.py --suite DCSA --module booking   # drill into one module

    # Customer mode — render your own hub ontology (any directory of Turtle). Reference-model
    # classes you import render as external stubs, labelled by their suite:
    python scripts/generate_ontology_diagrams.py --input path/to/my-hub/model --name "My Hub" --output my-hub.md
"""

from __future__ import annotations

import argparse
import difflib
import io
import sys
from pathlib import Path

from rdflib import Graph, RDF, RDFS, OWL, URIRef
from rdflib.collection import Collection

# Ensure UTF-8 output on Windows consoles (guarded so it never clobbers pytest capture).
if getattr(sys.stdout, "encoding", "").lower() != "utf-8" and hasattr(sys.stdout, "buffer"):
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace", line_buffering=True)

REPO_ROOT = Path(__file__).resolve().parent.parent
MODELS_ROOT = REPO_ROOT / "ontology-reference-models"
DERIVED_ROOT = MODELS_ROOT / "derived-ontologies"
DIAGRAMS_DIR = MODELS_ROOT / "diagrams"
OUTPUT_DIR = DIAGRAMS_DIR / "generated"

GENERATED_BANNER = (
    "<!-- GENERATED by scripts/generate_ontology_diagrams.py — DO NOT EDIT.\n"
    "     Regenerate with: python scripts/generate_ontology_diagrams.py\n"
    "     Source of truth: derived-ontologies/<suite>/current/**/*.ttl -->"
)


def suite_dirs() -> list[Path]:
    """Every derived suite directory that has a ``current/`` tree, sorted by name."""
    return sorted(
        (d for d in DERIVED_ROOT.iterdir() if d.is_dir() and (d / "current").is_dir()),
        key=lambda d: d.name.lower(),
    )


def load_suite_graph(suite_dir: Path) -> Graph:
    """Parse every Turtle file under ``<suite>/current/`` into one graph."""
    graph = Graph()
    for ttl in sorted((suite_dir / "current").rglob("*.ttl")):
        graph.parse(ttl, format="turtle")
    return graph


def ontology_base(graph: Graph) -> str:
    """The suite's base namespace, derived from its shortest owl:Ontology IRI.

    DCSA's root ontology is ``…/ont/dcsa`` and its modules are ``…/ont/dcsa/<module>``; the
    shortest ontology IRI is therefore the suite base every module URI shares.
    """
    onts = [str(s) for s in graph.subjects(RDF.type, OWL.Ontology) if isinstance(s, URIRef)]
    if not onts:
        return ""
    return min(onts, key=len)


def suite_bases() -> dict[str, str]:
    """Map every suite name to its base namespace, for classifying external references."""
    bases: dict[str, str] = {}
    for suite_dir in suite_dirs():
        base = ontology_base(load_suite_graph(suite_dir))
        if base:
            bases[suite_dir.name] = base
    return bases


def local_name(uri: str) -> str:
    """The fragment or last path segment of a URI, safe for a Mermaid identifier."""
    tail = uri.rsplit("#", 1)[-1] if "#" in uri else uri.rsplit("/", 1)[-1]
    return "".join(ch if (ch.isalnum() or ch == "_") else "_" for ch in tail)


def owning_suite(uri: str, bases: dict[str, str]) -> str | None:
    """Which suite (by name) owns ``uri``, matching the longest base namespace."""
    best: str | None = None
    best_len = -1
    for name, base in bases.items():
        if (uri == base or uri.startswith(base + "/") or uri.startswith(base + "#")) and len(base) > best_len:
            best, best_len = name, len(base)
    return best


def external_label(uri: str, bases: dict[str, str]) -> str:
    """A short prefix for a class owned by another suite / an authoritative source."""
    suite = owning_suite(uri, bases)
    if suite:
        return suite.lower()
    if "spec.edmcouncil.org/fibo" in uri:
        return "fibo"
    if "onerecord.iata.org" in uri:
        return "iata"
    if uri.startswith("https://www.kairosflow.ai/ont/blueprint"):
        return "blueprint"
    if uri.startswith("http://www.w3.org") or uri.startswith("http://purl.org"):
        return "rdf"
    return "ext"


def module_segment(uri: str) -> str:
    """The module name a class URI lives in — the path segment before its ``#`` fragment.

    ``…/ont/tic/locations#Berth`` -> ``locations``. Used to disambiguate two classes that
    share a local name across modules of the same suite.
    """
    left = uri.split("#", 1)[0]
    seg = left.rsplit("/", 1)[-1]
    return "".join(ch if (ch.isalnum() or ch == "_") else "_" for ch in seg)


def build_id_map(uris: set[URIRef], own_classes: set[URIRef], bases: dict[str, str]) -> dict[URIRef, str]:
    """Assign each URI a unique, stable Mermaid node id.

    Own classes get their bare local name; external classes a ``<prefix>__<local>`` id. When
    two URIs would collide on the same id (e.g. TIC's ``locations#Berth`` and
    ``terminal-infrastructure#Berth``), both are qualified with their module segment so the
    diagram never merges two distinct classes into one node.
    """
    preferred: dict[URIRef, str] = {}
    for uri in uris:
        s = str(uri)
        preferred[uri] = local_name(s) if uri in own_classes else f"{external_label(s, bases)}__{local_name(s)}"

    from collections import Counter
    counts = Counter(preferred.values())

    id_map: dict[URIRef, str] = {}
    for uri in uris:
        label = preferred[uri]
        if counts[label] > 1:
            label = f"{module_segment(str(uri))}_{label}"
        id_map[uri] = label
    return id_map


def expand_class_nodes(graph: Graph, node) -> list[URIRef]:
    """Resolve a domain/range node to the named classes it denotes.

    Handles a plain class URI and ``owl:unionOf`` collections; skips anonymous
    restrictions and datatype ranges.
    """
    if isinstance(node, URIRef):
        return [node]
    classes: list[URIRef] = []
    for union in graph.objects(node, OWL.unionOf):
        try:
            for member in Collection(graph, union):
                if isinstance(member, URIRef):
                    classes.append(member)
        except Exception:
            pass
    return classes


def collect(graph: Graph, base: str):
    """Extract the classes, inheritance edges and associations owned by this graph.

    ``base`` scopes ownership to a suite/ontology namespace. When it is empty (a customer
    ontology with no single root IRI to key on), every named ``owl:Class`` in the graph is
    treated as owned — the whole input is the diagram.
    """
    own_classes: set[URIRef] = set()
    for cls in graph.subjects(RDF.type, OWL.Class):
        if not isinstance(cls, URIRef):
            continue
        if not base or str(cls).startswith(base + "/") or str(cls).startswith(base + "#"):
            own_classes.add(cls)

    # Datatype-attribute count per owned class (keeps diagrams meeting-legible).
    attr_count: dict[URIRef, int] = {c: 0 for c in own_classes}
    for prop in graph.subjects(RDF.type, OWL.DatatypeProperty):
        for dom in graph.objects(prop, RDFS.domain):
            for cls in expand_class_nodes(graph, dom):
                if cls in attr_count:
                    attr_count[cls] += 1

    # Inheritance: only named-class superclasses (skip owl:Restriction blank nodes).
    subclass_edges: set[tuple[URIRef, URIRef]] = set()
    for cls in own_classes:
        for parent in graph.objects(cls, RDFS.subClassOf):
            if isinstance(parent, URIRef):
                subclass_edges.add((cls, parent))

    # Associations: object property domain -> range, expanding unions. An edge is kept when
    # either endpoint is an owned class, or when the *property* is owned by this suite — the
    # latter surfaces cross-suite bridge modules (e.g. SupplyChain) whose endpoints both live
    # in other suites.
    assoc_edges: set[tuple[URIRef, URIRef, str]] = set()
    for prop in graph.subjects(RDF.type, OWL.ObjectProperty):
        pname = local_name(str(prop))
        prop_owned = (not base) or str(prop).startswith(base + "/") or str(prop).startswith(base + "#")
        domains = [c for d in graph.objects(prop, RDFS.domain) for c in expand_class_nodes(graph, d)]
        ranges = [c for r in graph.objects(prop, RDFS.range) for c in expand_class_nodes(graph, r)]
        for dom in domains:
            for rng in ranges:
                if dom in own_classes or rng in own_classes or prop_owned:
                    assoc_edges.add((dom, rng, pname))

    return own_classes, attr_count, subclass_edges, assoc_edges


def render_suite(suite_name: str, module: str | None, bases: dict[str, str]) -> str:
    """Render one repository suite (optionally one module) to a Mermaid markdown document."""
    graph = load_suite_graph(DERIVED_ROOT / suite_name)
    base = ontology_base(graph)
    title = f"{suite_name}" + (f" / {module}" if module else "")
    return render_document(title, graph, base, bases, module)


def render_input(input_dir: Path, name: str | None, bases: dict[str, str]) -> str:
    """Render an arbitrary directory of Turtle (e.g. a customer's own hub ontology).

    Every ``*.ttl`` under ``input_dir`` is parsed into one graph. Classes owned by a Kairos
    reference suite (recognised by namespace) render as external stubs, so a customer diagram
    shows their own classes alongside the reference classes they import.
    """
    graph = Graph()
    for ttl in sorted(input_dir.rglob("*.ttl")):
        graph.parse(ttl, format="turtle")
    base = ontology_base(graph)
    banner = (
        "<!-- Generated by kairos-ontology-referencemodels "
        "scripts/generate_ontology_diagrams.py --input.\n"
        f"     Source: {input_dir} -->"
    )
    return render_document(name or input_dir.name, graph, base, bases, None, banner=banner)


def render_document(title: str, graph: Graph, base: str, bases: dict[str, str], module: str | None,
                    banner: str = GENERATED_BANNER) -> str:
    """Render a parsed graph to a Mermaid ``classDiagram`` markdown document."""
    own_classes, attr_count, subclass_edges, assoc_edges = collect(graph, base)

    if module:
        # Restrict to classes whose URI lives under …/<module> (the module namespace).
        mod_ns = f"{base}/{module}"
        own_classes = {
            c for c in own_classes
            if str(c).startswith(mod_ns + "#") or str(c).startswith(mod_ns + "/")
        }

    kept_sub = {(a, b) for (a, b) in subclass_edges if a in own_classes}
    if module:
        kept_assoc = {(a, b, p) for (a, b, p) in assoc_edges if a in own_classes or b in own_classes}
    else:
        # collect() already scoped associations to this graph (endpoint- or property-owned).
        kept_assoc = set(assoc_edges)

    # External nodes are any edge endpoint not in own_classes but referenced by a kept edge.
    external: set[URIRef] = set()
    for a, b in kept_sub:
        if b not in own_classes:
            external.add(b)
    for a, b, _ in kept_assoc:
        if a not in own_classes:
            external.add(a)
        if b not in own_classes:
            external.add(b)

    id_map = build_id_map(own_classes | external, own_classes, bases)

    def key(uri: URIRef) -> tuple[str, str]:
        # id_map ids are unique, so (id, uri) is a total order — fully deterministic.
        return (id_map[uri], str(uri))

    lines: list[str] = [banner, ""]
    lines.append(f"# {title} — class diagram")
    lines.append("")
    lines.append(f"Classes: {len(own_classes)} · inheritance: {len(kept_sub)} · associations: {len(kept_assoc)}")
    lines.append("")
    lines.append("```mermaid")
    lines.append("classDiagram")
    lines.append("  direction LR")

    # Own class nodes.
    for cls in sorted(own_classes, key=key):
        nid = id_map[cls]
        count = attr_count.get(cls, 0)
        if count:
            lines.append(f"  class {nid} {{")
            lines.append(f"    +{count} attributes")
            lines.append("  }")
        else:
            lines.append(f"  class {nid}")

    # External stub nodes with a stereotype annotation.
    for cls in sorted(external, key=key):
        nid = id_map[cls]
        lines.append(f"  class {nid}")
        lines.append(f"  <<{external_label(str(cls), bases)}>> {nid}")

    # Inheritance edges.
    for a, b in sorted(kept_sub, key=lambda e: (id_map[e[0]], id_map[e[1]])):
        lines.append(f"  {id_map[b]} <|-- {id_map[a]}")

    # Association edges.
    for a, b, p in sorted(kept_assoc, key=lambda e: (id_map[e[0]], e[2], id_map[e[1]])):
        lines.append(f"  {id_map[a]} --> {id_map[b]} : {p}")

    lines.append("```")
    lines.append("")
    return "\n".join(lines)


def render_index(bases: dict[str, str]) -> str:
    """Render the generated-diagram index README."""
    lines: list[str] = [GENERATED_BANNER, ""]
    lines.append("# Generated class diagrams")
    lines.append("")
    lines.append(
        "One Mermaid `classDiagram` per derived ontology suite, generated from "
        "`derived-ontologies/<suite>/current/**/*.ttl`. **Do not edit these files** — run "
        "`python scripts/generate_ontology_diagrams.py` to refresh them. Hand-authored "
        "conceptual diagrams live in [`../conceptual/`](../conceptual/)."
    )
    lines.append("")
    lines.append("| Suite | Base namespace | Diagram |")
    lines.append("|---|---|---|")
    for name in sorted(bases, key=str.lower):
        fname = f"{name.lower()}.md"
        lines.append(f"| {name} | `{bases[name]}` | [`{fname}`]({fname}) |")
    lines.append("")
    return "\n".join(lines)


def extract_mermaid_blocks(md_text: str) -> list[str]:
    """Return the body of every ```mermaid fenced block in ``md_text`` (fences excluded)."""
    blocks: list[str] = []
    lines = md_text.splitlines()
    i = 0
    while i < len(lines):
        if lines[i].strip() == "```mermaid":
            body: list[str] = []
            i += 1
            while i < len(lines) and lines[i].strip() != "```":
                body.append(lines[i])
                i += 1
            blocks.append("\n".join(body).rstrip() + "\n")
        i += 1
    return blocks


def mmd_targets_for(md_path: Path) -> list[tuple[Path, str]]:
    """Map a diagram ``.md`` file to the ``.mmd`` files it should produce.

    Raw ``.mmd`` files are a pure derivative of the committed ``.md`` (which is what GitHub
    renders): each fenced ``mermaid`` block becomes a standalone ``.mmd`` sibling so the source
    can be pasted into mermaid.live, a Confluence plugin or ``mmdc`` without stripping markdown.
    A single-block file yields ``<stem>.mmd``; a multi-block file yields ``<stem>.1.mmd`` … so
    every diagram maps to exactly one importable source file.
    """
    blocks = extract_mermaid_blocks(md_path.read_text(encoding="utf-8"))
    if not blocks:
        return []
    if len(blocks) == 1:
        return [(md_path.with_suffix(".mmd"), blocks[0])]
    return [
        (md_path.with_name(f"{md_path.stem}.{n}.mmd"), body)
        for n, body in enumerate(blocks, start=1)
    ]


def sync_mmd(check: bool) -> bool:
    """Write (or --check) a raw ``.mmd`` for every mermaid block under ``diagrams/``.

    Extracts from the ``.md`` on disk, so it runs *after* the generated ``.md`` are refreshed
    and treats the committed markdown as the single source of truth for both generated and
    hand-authored conceptual diagrams.
    """
    in_sync = True
    expected: set[Path] = set()
    for md_path in sorted(DIAGRAMS_DIR.rglob("*.md")):
        for mmd_path, body in mmd_targets_for(md_path):
            expected.add(mmd_path)
            in_sync &= write_or_check(mmd_path, body, check)
    # Flag orphaned .mmd files whose source block/file has gone away.
    for mmd_path in sorted(DIAGRAMS_DIR.rglob("*.mmd")):
        if mmd_path not in expected:
            in_sync = False
            if check:
                print(f"ORPHAN: {mmd_path.relative_to(REPO_ROOT)} (no matching mermaid block)")
            else:
                mmd_path.unlink()
                print(f"removed {mmd_path.relative_to(REPO_ROOT)}")
    return in_sync


def write_or_check(path: Path, content: str, check: bool) -> bool:
    """Write ``content`` to ``path`` (or diff in --check mode). Returns True if in sync."""
    existing = path.read_text(encoding="utf-8") if path.exists() else None
    if existing == content:
        return True
    if check:
        print(f"STALE: {path.relative_to(REPO_ROOT)}")
        diff = difflib.unified_diff(
            (existing or "").splitlines(),
            content.splitlines(),
            fromfile="on-disk",
            tofile="generated",
            lineterm="",
        )
        for line in list(diff)[:40]:
            print(f"  {line}")
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"wrote {path.relative_to(REPO_ROOT)}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate Mermaid class diagrams from ontology Turtle — either this "
        "repository's derived suites, or any external ontology directory via --input.",
    )
    parser.add_argument("--suite", help="Only process this repository suite (e.g. DCSA). Default: all.")
    parser.add_argument("--module", help="Drill into a single module of --suite (e.g. booking). Prints to stdout.")
    parser.add_argument("--check", action="store_true", help="Diff against disk without writing; non-zero exit on drift.")
    parser.add_argument(
        "--input", metavar="DIR",
        help="Render an external ontology directory (e.g. a customer's hub) instead of the "
        "repository suites. Parses every *.ttl beneath DIR. Prints to stdout unless --output is given.",
    )
    parser.add_argument("--name", help="Diagram title for --input mode (default: the input directory name).")
    parser.add_argument("--output", metavar="FILE", help="Write --input output to FILE instead of stdout.")
    args = parser.parse_args()

    bases = suite_bases()

    # Customer / external mode: render an arbitrary ontology directory.
    if args.input:
        input_dir = Path(args.input).expanduser().resolve()
        if not input_dir.is_dir():
            print(f"--input directory not found: {input_dir}")
            return 2
        if not any(input_dir.rglob("*.ttl")):
            print(f"No .ttl files found under {input_dir}")
            return 2
        content = render_input(input_dir, args.name, bases)
        if args.output:
            out = Path(args.output).expanduser().resolve()
            out.parent.mkdir(parents=True, exist_ok=True)
            out.write_text(content, encoding="utf-8")
            print(f"wrote {out}")
        else:
            print(content)
        return 0

    known = {d.name for d in suite_dirs()}

    if args.suite and args.suite not in known:
        print(f"Unknown suite '{args.suite}'. Known: {', '.join(sorted(known))}")
        return 2

    # Module drill-in is an on-demand view: print, never persisted.
    if args.module:
        if not args.suite:
            print("--module requires --suite")
            return 2
        print(render_suite(args.suite, args.module, bases))
        return 0

    targets = [args.suite] if args.suite else sorted(known, key=str.lower)
    in_sync = True
    for name in targets:
        content = render_suite(name, None, bases)
        path = OUTPUT_DIR / f"{name.lower()}.md"
        in_sync &= write_or_check(path, content, args.check)

    # The index is only regenerated on a full run (it lists every suite).
    if not args.suite:
        in_sync &= write_or_check(OUTPUT_DIR / "README.md", render_index(bases), args.check)
        # Raw .mmd exports are derived from the committed .md — refresh them last, on full runs.
        in_sync &= sync_mmd(args.check)

    if args.check and not in_sync:
        print("\nDiagrams are stale. Run: python scripts/generate_ontology_diagrams.py")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
